version: '3.8'

services:
  duplicator:
    build:
      context: .
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
    environment:
      - TARGET1=http://example1.local/api
      - TARGET2=http://example2.local/api
      - LOG_DIR=/logs
      - LISTEN_PORT=6000
      - FORWARD_TIMEOUT=5
    volumes:
      - ./logs:/logs
    expose:
      - "6000"

  nginx:
    image: docker.io/nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - duplicator
