version: "3.8"

services:
  duplicator_9401:
    image: http-duplicator:latest
    container_name: duplicator_9401
    environment:
      - LISTEN_PORT=9401
      - TARGET1=10.49.77.153:9501
      - TARGET2=10.49.77.153:9502
      - LOG_DIR=/logs
    ports:
      - "9401:9401"
    volumes:
      - /var/log/duplicator_logs/9401:/logs
