version: '3.8'

services:
  duplicator:
    build:
      context: .
    environment:
      - TARGET1=https://censhare-cons-de.bshg.com
      - TARGET2=https://csq2.bshg.com
      - LOG_DIR=/logs
      - LISTEN_PORT=6000
      - FORWARD_TIMEOUT=5
      - AUTH_USERNAME=censhare-rest
      - AUTH_PASSWORD=censhare-rest
      - NO_PROXY=localhost,127.0.0.1,duplicator,nginx,si0vm10431.bsh.corp.bshg.com,censhare-cons-de.bshg.com,csq2.bshg.com
    volumes:
      - ./logs:/logs
    expose:
      - "6000"

  nginx:
    image: docker.io/nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - duplicator
